BACKPORT: seccomp: add filter_count field for KernelSU
KernelSU requires struct seccomp to have atomic_t filter_count,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:
error: no member named 'filter_count' in 'struct seccomp'

Signed-off-by: THE-EGO-999-GT <theego999.me@gmail.com>